name = "lean-ufo"
version = "0.1.0"
defaultTargets = ["LeanUfo"]
testDriver = "LeanUfoTest"

[[lean_lib]]
name = "LeanUfo"

[[lean_exe]]
name = "LeanUfoTest"
root = "LeanUfoTest"

[[lean_exe]]
name = "export-certificates"
root = "LeanUfo.ExportCertificates"

[[lean_exe]]
name = "validate-certificate"
root = "LeanUfo.ValidateCertificate"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"
