import LeanUfo.UFO.Core.Signature3_9
import LeanUfo.UFO.Core.Section3_8
import Mathlib.Logic.ExistsUnique

universe u v

variable (Sig : UFOSignature3_9)

open UFOSignature3_9

/-
  §3.9 — Moments and inherence

  This section adds the inherence relation and the derived notions of
  moment-of and ultimate bearer.
-/

/--
(a65)

inheresIn(x, y) → ed(x, y)

Natural language:
Inherence implies existential dependence.
-/
def ax_a65 : Prop :=
  ∀ (x y : Sig.Thing) (w : Sig.F.World),
    Sig.InheresIn x y w →
      Sig.ExistentialDependence x y w

/--
(a66)

inheresIn(x, y) → Moment(x) ∧ (Type(y) ∨ ConcreteIndividual(y))

Natural language:
Whatever inheres in something is a moment, and its bearer is either a type or
a concrete individual.
-/
def ax_a66 : Prop :=
  ∀ (x y : Sig.Thing) (w : Sig.F.World),
    Sig.InheresIn x y w →
      (Sig.Moment x w ∧
       (Sig.Type_ y w ∨ Sig.ConcreteIndividual y w))

/--
(a67)

inheresIn(x, y) ∧ inheresIn(x, z) → y = z

Natural language:
A moment cannot inhere in two distinct bearers.
-/
def ax_a67 : Prop :=
  ∀ (x y z : Sig.Thing) (w : Sig.F.World),
    (Sig.InheresIn x y w ∧ Sig.InheresIn x z w) →
      y = z

/--
Definition (d2): moment of.

`momentOf(m, x)` is the transitive closure of inherence:
either `m` directly inheres in `x`, or `m` inheres in some `y` that is itself
a moment of `x`.

Read operationally, the paper's clause says:
- `m` is a moment of `x` if it directly inheres in `x`, or
- `m` inheres in some `y` which is itself a moment of `x`.

That is exactly what the two constructors below encode:
- `direct`: if `InheresIn m x`, then `MomentOf m x`,
- `step`: if `InheresIn m y` and `MomentOf y x`, then `MomentOf m x`.

We formalize this as an inductive relation generated by the two clauses of
(d2). In Lean, inductive predicates are specified by their constructors and are
reasoned about via the induction principle generated from them; see the Lean
Reference Manual, “Inductive Types”
(`<https://lean-lang.org/doc/reference/latest/The-Type-System/Inductive-Types/>`)
and Theorem Proving in Lean 4, “Inductive Types”
(`<https://docs.lean-lang.org/theorem_proving_in_lean4/Inductive-Types/>`).
We use this inductive presentation because the paper's formulation is
recursively self-referential, and Lean does not accept such a propositional
self-reference as an ordinary `def`.
-/
inductive MomentOf (Sig : UFOSignature3_9) :
    Sig.Thing → Sig.Thing → Sig.F.World → Prop where
  | direct {m x : Sig.Thing} {w : Sig.F.World} :
      Sig.InheresIn m x w →
      MomentOf Sig m x w
  | step {m y x : Sig.Thing} {w : Sig.F.World} :
      Sig.InheresIn m y w →
      MomentOf Sig y x w →
      MomentOf Sig m x w

/--
Definition (d3): ultimate bearer.

`ultimateBearerOf(b, m)` holds exactly when `b` is not a moment and `m` is a
moment of `b`.
-/
def UltimateBearerOf (Sig : UFOSignature3_9)
    (b m : Sig.Thing) (w : Sig.F.World) : Prop :=
  ¬ Sig.Moment b w ∧
  MomentOf Sig m b w

/--
(a68)

Moment(m) → ∃!b ultimateBearerOf(b, m)

Natural language:
Every moment has a unique ultimate bearer.

We use mathlib's `∃!` / `ExistsUnique` notation here.
-/
def ax_a68 : Prop :=
  ∀ (m : Sig.Thing) (w : Sig.F.World),
    Sig.Moment m w →
      ∃! b : Sig.Thing, UltimateBearerOf Sig b m w

/--
Auxiliary lemma for the inherence theorems:
if `m` inheres in itself, then every inherence chain starting from `m`
ends again at `m`.
-/
theorem momentOf_target_eq_of_self_inheres
  (hA67 : ax_a67 Sig) :
  ∀ {m x : Sig.Thing} {w : Sig.F.World},
    Sig.InheresIn m m w →
      MomentOf Sig m x w →
        x = m
  | m, x, w, hSelf, MomentOf.direct hInh =>
      (hA67 m m x w ⟨hSelf, hInh⟩).symm
  | m, x, w, hSelf, @MomentOf.step _ _ y _ _ hInh hTail =>
      have hyEq : y = m := by
        exact (hA67 m m y w ⟨hSelf, hInh⟩).symm
      match hyEq with
      | rfl =>
          momentOf_target_eq_of_self_inheres hA67 hSelf hTail

mutual

/--
Auxiliary lemma for `t29`:
in a two-node inherence cycle `x ↦ y ↦ x`, every `MomentOf` chain starting from
`x` ends either at `x` or at `y`.
-/
theorem momentOf_target_of_cycle_left
  (hA67 : ax_a67 Sig) :
  ∀ {x y b : Sig.Thing} {w : Sig.F.World},
    Sig.InheresIn x y w →
      Sig.InheresIn y x w →
        MomentOf Sig x b w →
          (b = x ∨ b = y)
  | x, y, b, w, hxy, hyx, MomentOf.direct hInh =>
      Or.inr (hA67 x y b w ⟨hxy, hInh⟩).symm
  | x, y, b, w, hxy, hyx, @MomentOf.step _ _ u _ _ hInh hTail =>
      by
        have huEq : u = y := by
          exact (hA67 x y u w ⟨hxy, hInh⟩).symm
        subst huEq
        exact momentOf_target_of_cycle_right hA67 hxy hyx hTail

/--
Auxiliary lemma for `t29`:
in a two-node inherence cycle `x ↦ y ↦ x`, every `MomentOf` chain starting from
`y` ends either at `x` or at `y`.
-/
theorem momentOf_target_of_cycle_right
  (hA67 : ax_a67 Sig) :
  ∀ {x y b : Sig.Thing} {w : Sig.F.World},
    Sig.InheresIn x y w →
      Sig.InheresIn y x w →
        MomentOf Sig y b w →
          (b = x ∨ b = y)
  | x, y, b, w, hxy, hyx, MomentOf.direct hInh =>
      Or.inl ((hA67 y x b w ⟨hyx, hInh⟩).symm)
  | x, y, b, w, hxy, hyx, @MomentOf.step _ _ u _ _ hInh hTail =>
      by
        have huEq : u = x := by
          exact (hA67 y x u w ⟨hyx, hInh⟩).symm
        subst huEq
        exact momentOf_target_of_cycle_left hA67 hxy hyx hTail

end

/--
(t28)

¬ inheresIn(x, x)

Natural language:
Inherence is non-reflexive.
-/
theorem th_t28
  (hA66 : ax_a66 Sig)
  (hA67 : ax_a67 Sig)
  (hA68 : ax_a68 Sig) :
  ∀ (x : Sig.Thing) (w : Sig.F.World),
    ¬ Sig.InheresIn x x w :=
by
  intro x w hSelf
  have hMom : Sig.Moment x w := (hA66 x x w hSelf).1
  rcases hA68 x w hMom with ⟨b, hUB, _hUnique⟩
  have hbEq : b = x := by
    exact momentOf_target_eq_of_self_inheres (Sig := Sig) hA67 hSelf hUB.2
  subst hbEq
  exact hUB.1 hMom

/--
(t29)

inheresIn(x, y) → ¬ inheresIn(y, x)

Natural language:
Inherence is asymmetric.
-/
theorem th_t29
  (hA66 : ax_a66 Sig)
  (hA67 : ax_a67 Sig)
  (hA68 : ax_a68 Sig) :
  ∀ (x y : Sig.Thing) (w : Sig.F.World),
    Sig.InheresIn x y w →
      ¬ Sig.InheresIn y x w :=
by
  intro x y w hxy hyx
  have hMomx : Sig.Moment x w := (hA66 x y w hxy).1
  have hMomy : Sig.Moment y w := (hA66 y x w hyx).1
  rcases hA68 x w hMomx with ⟨b, hUB, _hUnique⟩
  have hbCases : b = x ∨ b = y := by
    exact momentOf_target_of_cycle_left (Sig := Sig) hA67 hxy hyx hUB.2
  rcases hbCases with hbEq | hbEq
  · subst hbEq
    exact hUB.1 hMomx
  · subst hbEq
    exact hUB.1 hMomy

/--
(t30)

inheresIn(x, y) ∧ inheresIn(y, z) → ¬ inheresIn(x, z)

Natural language:
Inherence is anti-transitive.
-/
theorem th_t30
  (hA66 : ax_a66 Sig)
  (hA67 : ax_a67 Sig)
  (hA68 : ax_a68 Sig) :
  ∀ (x y z : Sig.Thing) (w : Sig.F.World),
    (Sig.InheresIn x y w ∧ Sig.InheresIn y z w) →
      ¬ Sig.InheresIn x z w :=
by
  intro x y z w h hxz
  rcases h with ⟨hxy, hyz⟩
  have hyEq : y = z := hA67 x y z w ⟨hxy, hxz⟩
  subst hyEq
  exact th_t28 (Sig := Sig) hA66 hA67 hA68 y w hyz

/--
Axioms package for §3.9.

Extends §3.8 axioms with:
- (a65) inherence implies existential dependence,
- (a66) inherence holds from moments to their bearers,
- (a67) uniqueness of bearer,
- (a68) existence and uniqueness of ultimate bearer.
-/
class UFOAxioms3_9 (Sig : UFOSignature3_9) : Prop
  extends UFOAxioms3_8 Sig.toUFOSignature3_8 where

  -- §3.9 axioms
  ax65 : ax_a65 Sig
  ax66 : ax_a66 Sig
  ax67 : ax_a67 Sig
  ax68 : ax_a68 Sig
